### ISSUE TITLE
unable to connect to project which has enabled datastore and cloud storage

### ISSUE THREAD

**Issue by mgenov** [verdaccio/verdaccio-google-cloud#10]
The plugins fails to connect to a project which has enabled datastore and cloud storage:
```
Verdaccio doesn't need superuser privileges. Don't run it under root.
 warn --- config file  - /conf/config.yaml
 warn -=- Using credentials in a file might be un-secure and is recommended for local development
 warn -=- Google storage settings: {"projectId":"myproject","keyFilename":"/run/secrets/gcs-key.json"}
 warn -=- Using credentials in a file might be un-secure and is recommended for local development
 warn -=- Google storage settings: {"projectId":"myproject","keyFilename":"/run/secrets/gcs-key.json"}
 warn --- Plugin successfully loaded: google-cloud
(node:12) UnhandledPromiseRejectionWarning: Error: 5 NOT_FOUND: The project myproject does not exist or it does not contain an active Cloud Datastore or Cloud Firestore database. Please visit http://console.cloud.google.com to create a project or https://console.cloud.google.com/datastore/setup?project=myproject to add a Cloud Datastore or Cloud Firestore database. Note that Cloud Datastore or Cloud Firestore always have an associated App Engine app and this app must not be disabled.
    at Object.exports.createStatusError (/usr/local/lib/node_modules/verdaccio-google-cloud/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/verdaccio-google-cloud/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/usr/local/lib/node_modules/verdaccio-google-cloud/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/usr/local/lib/node_modules/verdaccio-google-cloud/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/usr/local/lib/node_modules/verdaccio-google-cloud/node_modules/grpc/src/client_interceptors.js:845:24)
(node:12) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
child process exited with code 0
```

I suspect that it's issue related to gRPC  dependencies used by the plugin.

**Comment by juanpicado** [comment]
@mgenov are you still having this issue? I think the error is an external one. The plugin use a google library that handle auth and Google Cloud communication.
