### ISSUE TITLE
google-cloud plugin not found

### ISSUE THREAD

**Issue by dhillondeep** [verdaccio/verdaccio-google-cloud#3]
I have installed the plugin using:
```nodejs
npm install -g verdaccio-google-cloud
```
and then when I execute `verdaccio`, I am getting an error that the plugin is not found
```
(node:428) UnhandledPromiseRejectionWarning: Error: "google-cloud" plugin not found
try "npm install verdaccio-google-cloud"
    at /usr/lib/node_modules/verdaccio/build/lib/plugin-loader.js:88:13
    at Array.map (<anonymous>)
    at loadPlugin (/usr/lib/node_modules/verdaccio/build/lib/plugin-loader.js:62:43)
    at LocalStorage._loadStorePlugin (/usr/lib/node_modules/verdaccio/build/lib/local-storage.js:865:63)
    at LocalStorage._loadStorage (/usr/lib/node_modules/verdaccio/build/lib/local-storage.js:849:26)
    at new LocalStorage (/usr/lib/node_modules/verdaccio/build/lib/local-storage.js:64:27)
    at Storage.init (/usr/lib/node_modules/verdaccio/build/lib/storage.js:73:25)
    at /usr/lib/node_modules/verdaccio/build/api/index.js:140:19
    at Generator.next (<anonymous>)
    at step (/usr/lib/node_modules/verdaccio/build/api/index.js:47:191)
(node:428) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:428) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by juanpicado** [comment]
Check your node installation, it works using `nvm`. 
```
➜ npm install -g verdaccio-google-cloud
+ verdaccio-google-cloud@0.0.7
added 2 packages from 4 contributors and updated 7 packages in 45.05s

npm on  latest [?] is 📦 v6.1.0 via ⬢ v9.9.0 at ☸️  minikube took 46s 
➜ verdaccio --listen localhost:9000
 warn --- config file  - /Users/user/.config/verdaccio/config.yaml
 warn -=- Using credentials in a file might be un-secure and is recommended for local development
 warn -=- Google storage settings: {"projectId":"verdaccio-01","keyFilename":"/Users/user/.config/verdaccio/xxxx-01-xxxx.json"}
 warn -=- Using credentials in a file might be un-secure and is recommended for local development
 warn -=- Google storage settings: {"projectId":"verdaccio-01","keyFilename":"/Users/user/.config/verdaccio/xxxx-01-xxxx.json"}
 warn --- Plugin successfully loaded: google-cloud
 warn --- Plugin successfully loaded: htpasswd
 warn --- Plugin successfully loaded: audit
 warn --- http address - http://localhost:9000/ - verdaccio/3.1.1
 debug-=- gcloud: reading package for verdaccio-google-cloud
 debug-=- gcloud: reading package for verdaccio-google-cloud
 debug-=- gcloud: verdaccio-google-cloud package not found on storage
 debug-=- gcloud: read package verdaccio-google-cloud has failed err: no such package
 debug-=- gcloud: verdaccio-google-cloud package not found on storage
 debug-=- gcloud: read package verdaccio-google-cloud has failed err: no such package
```

**Comment by dhillondeep** [comment]
I will try again and will get back to you. I have `nvm` too

**Comment by dhillondeep** [comment]
It works fine on linux and mac. I was testing on windows subsystem so it could have been my nodejs install
